### ISSUE TITLE
Changing Requirements

### ISSUE THREAD

**Issue by go-christianharrel** [PUP-BSIT/project-vrzn_appdev#22]
### Discussed in https://github.com/PUP-BSIT/project-vrzn_appdev/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **go-christianharrel** May 30, 2024</sup>
I've updated our system requirements documentation. Could you please review it and let me know if meron pa tayong need i-update. You may see it on our [development branch](https://github.com/PUP-BSIT/project-vrzn_appdev/tree/development). Thanks, @Galope-Jhean!</div>

**Comment by Galope-Jhean** [comment]
lgtm

**Comment by Galope-Jhean** [comment]
closing this comment
