### ISSUE TITLE
Use a service class

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-vrzn_appdev#24]
Create a service to implement HTTP requests. Do not use the HttpClient directly in the component.
https://github.com/PUP-BSIT/project-vrzn_appdev/blob/36afbaef152e45bfc3f8040504f31e2accd28ff6/SpaceShare.UI/src/app/app.component.ts#L13

Do not use the Object type. It is equivalent to using any type.
https://github.com/PUP-BSIT/project-vrzn_appdev/blob/36afbaef152e45bfc3f8040504f31e2accd28ff6/SpaceShare.UI/src/app/app.component.ts#L17

Added to Coding guidelines.
https://docs.google.com/presentation/d/1Mdcq3WcHksBlbCvxi6wx5vajn4v8LGlJRnBIu3x4fvw/edit#slide=id.g2e07e82d92c_1_1

**Comment by go-christianharrel** [comment]
We will apply these changes along with the pull request. Thank you so much, sir!

**Comment by Galope-Jhean** [comment]
changes applied @ e2e0250d2a62e13acf9c6a8fc3de62302c88d689

1. defined a method in a service class that returns an observable of type [TestModel](https://github.com/PUP-BSIT/project-vrzn_appdev/blob/e2e0250d2a62e13acf9c6a8fc3de62302c88d689/SpaceShare.UI/model/TestModel.ts)

https://github.com/PUP-BSIT/project-vrzn_appdev/blob/07aa719cb1794b324606c45e31b09ee87a9fe029/SpaceShare.UI/src/app/app.service.ts#L14-L16

2. called that service inside the component class and subscribed from there

https://github.com/PUP-BSIT/project-vrzn_appdev/blob/e2e0250d2a62e13acf9c6a8fc3de62302c88d689/SpaceShare.UI/src/app/app.component.ts#L11-L17

**Comment by Galope-Jhean** [comment]
@ssvillarosa, just seeking guidance about approaching this better. 

The concept of RxJS is new to me but from my understanding, I could also approach this with `async/await`. 

In which circumstances would each be appropriate?

Thanks.

**Comment by ssvillarosa** [comment]
Good evening Mr. Galope,

Angular use Observables heavily. Although there is no strict rule when to use async/await over observables, using observables offers more advantage You may not need it now but as you progress during the development and your experience grow larger, you will slowly understand the need to use observables over async/await. Since Angular use observables heavily, it somewhat implies that we should use observables not only for uniformity but for the extra features it offers especially the RXJS operators. Angular use observables and let's utilize it in this framework.

See my example [PR ](https://github.com/PUP-BSIT/project-hypefive_appdev/pull/14/files)with your classmate. With VanillaJS, you can use addEventListener and querySelector to implement browser events handling. However, Angular offers a better approach which is event and data binding to simplify the code. Compare the codes before and after my changes. I hope you see a cleaner, simpler, and more readable code with my changes. In the same way, Angular makes use of observable as it satisfies the purpose of its framework which is simpler, cleaner, and more maintainable code. In Angular, you use observables and in VanillaJS, use async/await.

**Comment by ssvillarosa** [comment]
If you are also interested, here are some guidelines that Google is using for [HTML/CSS](https://google.github.io/styleguide/htmlcssguide.html), [JS](https://google.github.io/styleguide/jsguide.html), and [Angular](https://google.github.io/styleguide/angularjs-google-style.html). Some of our coding guidelines are based on that. I know it's overwhelming that's why we developed our own guidelines and discuss you an additional point every session. I encourage you to read this if you have spare time.

**Comment by Galope-Jhean** [comment]
Thank you for the guidance. I am still getting familiar with RxJS and so far I see the importance and flexibility that it offers in many situations. I will definitely check out the guidelines you provided and make sure I understand them. Thanks again!
