### ISSUE TITLE
Development Workflow

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-vrzn_appdev#3]
I told you to not commit directly on the main branch. You need to do pull request for every changes. Kindly see below document.
https://docs.google.com/presentation/d/1xG5x-A4_CalyCDfSTWFWn44P_wrC9zzNHxJnE1PwG84/edit#slide=id.g2dd3d877e27_0_23

Next time that you will not follow our process, you will get demerit points.

**Comment by go-christianharrel** [comment]
Understood, sir. We'll be incorporating pull requests for every change to our production environment (main branch) for the next push we do. For now, we have added protection to our main branch. Thank you, sir!
