### ISSUE TITLE
No progress update and retrospective for sprint 1

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-vrzn_appdev#4]
https://docs.google.com/presentation/d/1xG5x-A4_CalyCDfSTWFWn44P_wrC9zzNHxJnE1PwG84/edit?usp=sharing
0.1 demerit point for each member.

**Comment by go-christianharrel** [comment]
This is acknowledged, sir. Apologies for the misunderstanding on our part. We'll be uploading the update/progress report for 'Sprint 0' within the day. This week, we will formally start Sprint 1. Thank you for your guidance, sir.
